[package]
name = "libdav"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.0"
domain = { version = "0.7.2", features = ["resolv"] }
http = "0.2.9"
hyper = { version = "0.14.24", features = ["http1", "client"] }
hyper-rustls = "0.23.2"
quick-xml = { version = "0.27.0" }
thiserror = "1.0.38"
tokio = "1.25.0"
