image: alpine/edge
packages:
  - cargo
  - rust
  - rustfmt
  - rust-clippy
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
secrets:
  - 2d3090e6-72a6-4d00-8221-92184d276c90 # rsync@anchor
tasks:
  - prepare: |
      cd vdirsyncer-rs
      cargo fetch --locked  # make sure lockfile is up to date
  - build: |
      cd vdirsyncer-rs
      cargo build
  - lint: |
      cd vdirsyncer-rs
      cargo fmt --check
      cargo clippy
  - test: |
      cd vdirsyncer-rs
      cargo test  # includes examples and doctests
  - doc: |
      cd vdirsyncer-rs
      cargo doc  # fails on broken links
  - publish-doc: |
      cd vdirsyncer-rs
      [ $(git rev-parse --abbrev-ref HEAD) = main ] || complete-build
      echo "anchor.whynothugo.nl ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIE2WacYpYEP5vvevx4NXQn3Ktd53pBkZR/bpPoS3Wkyg" > $HOME/.ssh/known_hosts
      rsync -r target/doc/ rsync@anchor.whynothugo.nl:./
