image: archlinux
packages:
  - rustup
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - prepare: |
      cd vdirsyncer-rs
      cargo fetch --locked  # make sure lockfile is up to date
  - build: |
      cd vdirsyncer-rs
      cargo build
  - lint: |
      cd vdirsyncer-rs
      cargo fmt --check
      cargo clippy
  - test: |
      cd vdirsyncer-rs
      cargo test  # this includes examples and doctests
  - doc: |
      cd vdirsyncer-rs
      cargo doc  # fails on broken links
