image: archlinux
packages:
  - rustup
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - build: |
      cd vdirsyncer-rs
      cargo build
      cargo build --examples
  - lint: |
      cd vdirsyncer-rs
      cargo fmt --check
      cargo clippy
  - test: |
      cd vdirsyncer-rs
      cargo test
      cargo test --doc
  - doc: |
      cd vdirsyncer-rs
      cargo doc
