image: archlinux
packages:
  - rustup
environment:
  CARGO_TERM_COLOR: always
triggers:
  - action: email
    condition: failure
    to: Hugo Osvaldo Barrera <hugo@whynothugo.nl>
tasks:
  - build: |
      cd vdirsyncer-rs
      cargo build
  - lint: |
      cd vdirsyncer-rs
      cargo clippy
  - test: |
      cd vdirsyncer-rs
      cargo test
      cargo test --doc
